---
deployment:
  tasks:
    - export DEPLOYPATH=/home/arhiwrrs/api.polygis.xyz
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp sqlconnection.js $DEPLOYPATH
    - /bin/cp authentication.js $DEPLOYPATH